import type { Doc, Profile, University } from "./univero";

export type GeminiEvaluation = {
  overallVerdict: "Strong Candidate" | "Competitive / Target" | "Reach School" | "High Reach" | "Prerequisites Missing";
  estimatedAcceptanceProbability: number; // e.g. 75 (%)
  summary: string;
  keyStrengths: string[];
  areasOfConcern: string[];
  actionPlan: string[];
  scholarshipOutlook: string;
  recommendedProgramFocus: string;
};

// Returns stored or environment GEMINI_API_KEY
export function getGeminiApiKey(): string {
  if (typeof window !== "undefined") {
    const userStored = localStorage.getItem("univero-gemini-key");
    if (userStored && userStored.trim()) return userStored.trim();
    // @ts-expect-error Vite env
    if (typeof import.meta !== "undefined" && import.meta.env?.VITE_GEMINI_API_KEY) {
      // @ts-expect-error Vite env
      return import.meta.env.VITE_GEMINI_API_KEY;
    }
  }
  if (typeof process !== "undefined" && process.env) {
    return process.env.GEMINI_API_KEY || process.env.VITE_GEMINI_API_KEY || "";
  }
  return "";
}

export function saveGeminiApiKey(key: string) {
  if (typeof window !== "undefined") {
    if (key.trim()) {
      localStorage.setItem("univero-gemini-key", key.trim());
    } else {
      localStorage.removeItem("univero-gemini-key");
    }
  }
}

// Call Gemini 2.5 Flash / 1.5 Flash via standard fetch
async function callGeminiApi(prompt: string, systemInstruction?: string): Promise<string> {
  const apiKey = getGeminiApiKey();
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not set. Please add GEMINI_API_KEY to your Vercel Environment Variables or settings.");
  }

  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;

  const body: {
    contents: Array<{ parts: Array<{ text: string }> }>;
    systemInstruction?: { parts: Array<{ text: string }> };
    generationConfig?: { temperature: number };
  } = {
    contents: [{ parts: [{ text: prompt }] }],
    generationConfig: {
      temperature: 0.3,
    },
  };

  if (systemInstruction) {
    body.systemInstruction = {
      parts: [{ text: systemInstruction }],
    };
  }

  const response = await fetch(endpoint, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    const errText = await response.text();
    // If 2.5-flash isn't available for this key, fallback to 1.5-flash
    if (response.status === 404 || response.status === 400) {
      const fallbackEndpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;
      const fallbackResponse = await fetch(fallbackEndpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      if (fallbackResponse.ok) {
        const fallbackData = await fallbackResponse.json();
        const text = fallbackData.candidates?.[0]?.content?.parts?.[0]?.text;
        if (text) return text;
      }
    }
    throw new Error(`Gemini API error (${response.status}): ${errText}`);
  }

  const data = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) {
    throw new Error("No response generated by Gemini");
  }
  return text;
}

/**
 * Intelligent University Admissions Decision Engine
 * Reads all student data, test scores, curriculum, grades, documents and evaluates chances at the specific university.
 */
export async function evaluateWithGemini(
  university: University,
  profile: Profile,
  docs: Doc[],
  specificProgram?: string
): Promise<GeminiEvaluation> {
  const targetProgram = specificProgram
    ? university.programs.find(p => p.name === specificProgram || p.id === specificProgram) || university.programs[0]
    : university.programs[0];

  const studentSummary = {
    name: profile.name || "Student",
    nationality: profile.nationality || "International",
    school: profile.school,
    curriculum: profile.curriculum,
    gpa: profile.gpa,
    gradeScale: profile.gradeScale,
    standardizedTests: [
      profile.sat ? `SAT: ${profile.sat}` : null,
      profile.act ? `ACT: ${profile.act}` : null,
      profile.ielts ? `IELTS: ${profile.ielts}` : null,
      profile.toefl ? `TOEFL: ${profile.toefl}` : null,
      ...profile.tests.map(t => `${t.name}: ${t.score || "Planned"} (${t.status})`),
    ].filter(Boolean),
    schoolYears: profile.years.map(y => ({
      year: y.label,
      type: y.kind,
      subjects: y.subjects.map(s => `${s.name}: ${s.grade}`).join(", "),
    })),
    extracurriculars: profile.activities.map(a => `${a.role} at ${a.org || a.title} (${a.hours} hrs/wk)`),
    workExperience: profile.work.map(w => `${w.role} at ${w.org}`),
    awards: profile.awards.map(aw => `${aw.title} - ${aw.org}`),
    skills: profile.skills,
    languages: profile.languages.map(l => `${l.name} (${l.level})`),
    careerGoal: profile.careerGoal,
    budgetPerYearEur: profile.budget,
    needsScholarship: profile.scholarship,
    uploadedDocuments: docs.map(d => `${d.type}: ${d.fileName} (${d.status})`),
  };

  const uniSummary = {
    university: university.name,
    country: university.country,
    city: university.city,
    type: university.type,
    selectivityTier: university.tier,
    tuitionEur: targetProgram ? targetProgram.tuition : university.tuition,
    tuitionEUEur: targetProgram ? targetProgram.tuitionEU : university.tuitionEU,
    programName: targetProgram ? targetProgram.name : university.program,
    indicativeGpa: targetProgram ? targetProgram.minGpa : university.minGpa,
    satRequired: university.satRequired,
    indicativeSat: targetProgram?.sat || university.sat,
    requiredIelts: targetProgram?.ielts || university.ielts,
    requiredSubjects: targetProgram?.requiredSubjects || [],
    livingCostEur: university.living,
  };

  const systemInstruction = `You are an elite, fair, and deeply knowledgeable international university admissions director and academic research counselor.
Your task is to analyze the student's complete academic record, test scores, extracurriculars, budget, and uploaded documents against the target university's rigorous admissions standards.
You must return your analysis strictly as a valid JSON object matching the requested schema. No markdown ticks, just JSON.`;

  const prompt = `Evaluate student profile for admission to ${university.name}:

STUDENT PROFILE:
${JSON.stringify(studentSummary, null, 2)}

UNIVERSITY & PROGRAM:
${JSON.stringify(uniSummary, null, 2)}

Analyze and return ONLY a JSON object with this exact structure:
{
  "overallVerdict": "Strong Candidate" | "Competitive / Target" | "Reach School" | "High Reach" | "Prerequisites Missing",
  "estimatedAcceptanceProbability": number between 5 and 95,
  "summary": "2-3 crisp sentences summarizing their realistic chances and fit",
  "keyStrengths": ["Strength 1", "Strength 2", "Strength 3"],
  "areasOfConcern": ["Concern or gap 1", "Concern or gap 2"],
  "actionPlan": ["Actionable step 1 for their application", "Actionable step 2", "Actionable step 3"],
  "scholarshipOutlook": "Realistic evaluation of scholarship chances and financial affordability",
  "recommendedProgramFocus": "Recommended specialization, major focus or essay angle that fits them best"
}`;

  try {
    const rawText = await callGeminiApi(prompt, systemInstruction);
    // Strip possible markdown code fence
    const cleanJson = rawText.replace(/```json/gi, "").replace(/```/g, "").trim();
    const parsed = JSON.parse(cleanJson) as GeminiEvaluation;
    return parsed;
  } catch (err) {
    console.error("Gemini evaluation error:", err);
    throw err;
  }
}

/**
 * Interactive Gemini University Counselor Chat
 */
export async function askGeminiCounselor(
  question: string,
  university: University,
  profile: Profile,
  conversationHistory: Array<{ role: "user" | "model"; text: string }> = []
): Promise<string> {
  const systemInstruction = `You are Univero's AI Academic Counselor powered by Google Gemini.
You have access to the student's background (${profile.name || "Student"}, GPA: ${profile.gpa || "N/A"}, Curriculum: ${profile.curriculum || "N/A"}, Nationality: ${profile.nationality || "N/A"}, Career goal: ${profile.careerGoal || "N/A"}).
You are advising them on ${university.name} in ${university.city}, ${university.country}.
Be encouraging, realistic, accurate about admissions and coursework, and highly strategic. Keep answers concise, actionable, and formatted in clean markdown.`;

  const historyContext = conversationHistory
    .map(h => `${h.role === "user" ? "Student" : "Counselor"}: ${h.text}`)
    .join("\n\n");

  const prompt = `${historyContext ? `Conversation so far:\n${historyContext}\n\n` : ""}Student asks: "${question}"`;

  return await callGeminiApi(prompt, systemInstruction);
}
