import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useUnivero } from "@/lib/use-univero";
import { universities, getMatch, money, type University } from "@/lib/univero";

export const Route = createFileRoute("/compare")({ head: () => ({ meta: [{ title: "Compare universities — Univero" }, { name: "description", content: "Compare up to three university programs by fit, eligibility, tuition, requirements and more." }, { property: "og:title", content: "Compare universities — Univero" }, { property: "og:description", content: "See the differences between your university matches side by side." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Compare });
function Compare() {
  const { profile, compare, ready, toggleCompare } = useUnivero(); const selected = compare.map(id => universities.find(u => u.id === id)).filter((u): u is University => Boolean(u));
  const rows: [string, (u: University) => string][] = [["Match score", u => `${getMatch(u, profile).score}%`], ["Eligibility", u => getMatch(u, profile).eligibility], ["Competitiveness", u => u.competitiveness], ["Country", u => u.country], ["City", u => u.city], ["Program", u => u.program], ["Tuition / year*", u => money(u.tuition)], ["Living costs / year*", u => `~${money(u.living)}`], ["Scholarships", u => u.scholarship ? "May be available" : "Not listed"], ["Language", u => u.language], ["Indicative GPA", u => `${u.minGpa}+`], ["Indicative SAT", u => `${u.sat}+`], ["Indicative IELTS", u => `${u.ielts}+`], ["Mathematics", u => u.math ? "Expected" : "Not required"], ["Career opportunities", u => u.career], ["Student population", u => u.students], ["Setting", u => u.setting], ["Personal fit", u => u.tags.slice(0, 2).join(", ")]];
  return <main className="page-shell min-h-[70vh] py-12 md:py-16"><p className="text-xs font-bold uppercase text-primary">Side by side</p><h1 className="mt-3 font-display text-3xl font-bold text-ink md:text-4xl">Compare universities</h1><p className="mt-3 text-muted-foreground">The details that matter, all in one place. Compare up to three options.</p>{ready && !selected.length ? <div className="mt-12 rounded-lg border border-border bg-card px-6 py-16 text-center"><h2 className="font-display text-xl font-bold text-ink">Your comparison is empty</h2><p className="mt-2 text-sm text-muted-foreground">Add universities from your matches to see them side by side.</p><Button asChild className="mt-6"><Link to="/results">Explore matches <ArrowRight /></Link></Button></div> : <><div className="mt-9 overflow-x-auto rounded-lg border border-border bg-card"><table className="w-full min-w-[640px] border-collapse text-left text-sm"><thead><tr className="bg-secondary/60"><th className="w-[180px] p-4 align-top text-xs uppercase text-muted-foreground">Compare</th>{selected.map(u => <th key={u.id} className="min-w-[200px] p-4 align-top"><div className="flex justify-between gap-2"><Link to="/university/$id" params={{ id: u.id }} className="font-display text-base font-bold text-ink hover:text-primary">{u.name}</Link><Button size="icon" variant="ghost" title={`Remove ${u.name}`} onClick={() => toggleCompare(u.id)} className="size-7 shrink-0"><X /></Button></div><p className="mt-1 text-xs font-normal text-muted-foreground">{u.city}, {u.country}</p></th>)}</tr></thead><tbody>{rows.map(([label, value], i) => <tr key={label} className={i % 2 ? "bg-muted/40" : ""}><th className="border-t border-border p-4 text-xs font-semibold text-muted-foreground">{label}</th>{selected.map(u => <td key={u.id} className={`border-t border-border p-4 ${i === 0 ? "font-display text-2xl font-bold text-primary" : "text-foreground"}`}>{value(u)}</td>)}</tr>)}</tbody></table></div><div className="mt-6 flex flex-wrap items-center justify-between gap-4"><p className="text-xs text-muted-foreground">*Illustrative prototype data. Confirm figures and requirements with universities.</p><Button variant="outline" asChild><Link to="/results">{selected.length < 3 ? "Add more universities" : "Back to matches"} <ArrowRight /></Link></Button></div></>}</main>;
}