import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, GraduationCap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useUnivero } from "@/lib/use-univero";
import { money, type Profile } from "@/lib/univero";

export const Route = createFileRoute("/onboarding")({ head: () => ({ meta: [{ title: "Your profile — Univero" }, { name: "description", content: "Tell Univero about your education, goals, budget and preferences to discover fitting universities." }, { property: "og:title", content: "Create your profile — Univero" }, { property: "og:description", content: "Your path to a personalized university shortlist starts here." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ProfilePage });
const steps = ["Education", "Tests", "Study plans", "Location", "Budget", "Preferences"];
const locations = ["Europe", "United Kingdom", "United States", "Netherlands", "Italy", "Spain", "Germany", "France", "Scandinavia", "Anywhere"];
const preferences = ["Big city", "Smaller university town", "Large university", "Smaller community", "International environment", "Strong career opportunities", "Campus life", "Prestige/ranking", "Affordable living costs", "Study abroad opportunities"];
function ProfilePage() {
  const navigate = useNavigate(); const { profile, updateProfile, ready } = useUnivero(); const [step, setStep] = useState(0); const [matching, setMatching] = useState(false);
  const set = <K extends keyof Profile>(key: K, value: Profile[K]) => updateProfile({ ...profile, [key]: value });
  const toggle = (key: "countries" | "preferences", item: string) => set(key, profile[key].includes(item) ? profile[key].filter(x => x !== item) : [...profile[key], item]);
  const next = () => { if (step < 5) { setStep(step + 1); window.scrollTo(0, 0); } else { setMatching(true); window.setTimeout(() => navigate({ to: "/results" }), 1500); } };
  if (!ready) return <div className="page-shell min-h-[60vh]" />;
  if (matching) return <main className="page-shell flex min-h-[65vh] flex-col items-center justify-center text-center"><div className="flex size-20 animate-pulse items-center justify-center rounded-lg bg-accent text-primary"><GraduationCap className="size-9" /></div><h1 className="mt-8 font-display text-3xl font-bold text-ink">Finding your best university matches…</h1><p className="mt-3 text-muted-foreground">Bringing your academics, goals and budget together.</p><div className="mt-8 h-1.5 w-48 overflow-hidden rounded-full bg-secondary"><div className="h-full w-2/3 animate-pulse rounded-full bg-primary" /></div></main>;
  return <main className="page-shell min-h-[75vh] py-12 md:py-16"><div className="mx-auto max-w-[750px]"><div className="flex items-center justify-between text-sm"><span className="font-bold text-primary">YOUR PROFILE</span><span className="text-muted-foreground">Step {step + 1} of 6</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary transition-all duration-300" style={{ width: `${(step + 1) / 6 * 100}%` }} /></div><div className="mt-5 hidden justify-between gap-2 text-xs text-muted-foreground sm:flex">{steps.map((s, i) => <span key={s} className={i === step ? "font-bold text-primary" : ""}>{s}</span>)}</div>
    <div className="mt-10 rounded-lg border border-border bg-card p-6 subtle-shadow md:p-10"><p className="text-xs font-bold uppercase text-primary">{steps[step]} · 0{step + 1}/06</p><h1 className="mt-3 font-display text-2xl font-bold text-ink md:text-3xl">{["Let’s start with your education.", "What tests have you taken?", "What would you like to study?", "Where can you see yourself?", "What’s your tuition budget?", "What matters most to you?"][step]}</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">{["This helps us understand your academic starting point.", "Only add scores you know. You can always update them later.", "Tell us what interests you, even if you’re still exploring.", "Select as many destinations as you’d consider.", "Think about annual tuition, excluding living expenses.", "Pick the things that make a university feel right for you."][step]}</p>
      <div className="mt-8 space-y-5">
      {step === 0 && <><Field label="Current country"><input className="input-field" value={profile.country} onChange={e => set("country", e.target.value)} placeholder="e.g. Estonia" /></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="School curriculum"><select className="input-field" value={profile.curriculum} onChange={e => set("curriculum", e.target.value)}><option value="">Select curriculum</option>{["National curriculum", "IB Diploma", "A Levels", "AP / US High School", "European Baccalaureate", "Other"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="GPA (4.0 scale, if available)"><input className="input-field" type="number" min="0" max="4" step="0.1" value={profile.gpa} onChange={e => set("gpa", e.target.value)} placeholder="e.g. 3.7" /></Field></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Graduation year"><input className="input-field" type="number" min="2024" max="2040" value={profile.graduation} onChange={e => set("graduation", e.target.value)} /></Field><label className="flex items-end gap-3 pb-3 text-sm font-medium"><input type="checkbox" className="size-4 accent-primary" checked={profile.math} onChange={e => set("math", e.target.checked)} /> I have studied mathematics</label></div></>}
      {step === 1 && <><label className="flex items-center gap-3 rounded-md border border-border p-4 text-sm"><input type="checkbox" className="size-4 accent-primary" checked={profile.noTests} onChange={e => set("noTests", e.target.checked)} /> I haven’t taken these tests</label><div className="grid gap-5 sm:grid-cols-2">{([["SAT score", "sat", "1600"], ["ACT score", "act", "36"], ["IELTS score", "ielts", "9"], ["TOEFL score", "toefl", "120"]] as const).map(([label, key, max]) => <Field key={key} label={label}><input disabled={profile.noTests} className="input-field disabled:opacity-50" type="number" min="0" max={max} step={key === "ielts" ? ".5" : "1"} value={profile[key]} onChange={e => set(key, e.target.value)} placeholder="Optional" /></Field>)}</div></>}
      {step === 2 && <><Field label="Intended field of study"><select className="input-field" value={profile.subject} onChange={e => set("subject", e.target.value)}>{["Business", "Economics", "Computer Science", "Engineering", "Psychology", "Law", "Medicine", "Design", "Arts & Humanities", "Not sure yet"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Preferred program (optional)"><input className="input-field" value={profile.program} onChange={e => set("program", e.target.value)} placeholder="e.g. International Business" /></Field><Field label="Degree level"><select className="input-field" value={profile.degree} onChange={e => set("degree", e.target.value)}><option>Bachelor’s</option><option>Master’s</option><option>Other</option></select></Field></>}
      {step === 3 && <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{locations.map(x => <Button key={x} variant={profile.countries.includes(x) ? "secondary" : "outline"} className="h-auto min-h-12 whitespace-normal px-3 py-2 text-left" onClick={() => toggle("countries", x)}>{profile.countries.includes(x) && <Check />} {x}</Button>)}</div>}
      {step === 4 && <><div className="rounded-md bg-secondary p-6 text-center"><span className="text-sm text-muted-foreground">Maximum annual tuition</span><div className="mt-2 font-display text-4xl font-bold text-primary">{money(profile.budget)}</div><input aria-label="Maximum tuition per year" type="range" min="0" max="80000" step="1000" value={profile.budget} onChange={e => set("budget", Number(e.target.value))} className="mt-7 w-full accent-primary" /><div className="mt-1 flex justify-between text-xs text-muted-foreground"><span>€0</span><span>€80,000+</span></div></div><label className="flex items-center gap-3 text-sm"><input type="checkbox" className="size-4 accent-primary" checked={profile.scholarship} onChange={e => set("scholarship", e.target.checked)} /> Scholarships or financial aid are important to me</label></>}
      {step === 5 && <div className="flex flex-wrap gap-2">{preferences.map(x => <Button key={x} variant={profile.preferences.includes(x) ? "secondary" : "outline"} className="h-auto min-h-11 whitespace-normal px-4 py-2" onClick={() => toggle("preferences", x)}>{profile.preferences.includes(x) && <Check />} {x}</Button>)}</div>}
      </div><div className="mt-10 flex items-center justify-between border-t border-border pt-6"><Button variant="ghost" disabled={step === 0} onClick={() => setStep(step - 1)}><ArrowLeft /> Back</Button><Button onClick={next}>{step === 5 ? "Find my matches" : "Continue"} <ArrowRight /></Button></div></div><p className="mt-5 text-center text-xs text-muted-foreground">Prototype recommendations use illustrative university data and are not admissions advice.</p></div></main>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-sm font-semibold text-foreground">{label}</span>{children}</label>; }