import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, type ReactNode } from "react";
import { Plus, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, Checklist, meta, PageHeader, Progress } from "@/components/univero/bits";
import { completeness, countries as uniCountries, curricula, emptyEntry, gradeScales, languageLevels, subjects, testNames, uid, type Entry, type Profile, type SchoolYear, type TestEntry } from "@/lib/univero";
import { useUnivero } from "@/lib/use-univero";

export const Route = createFileRoute("/profile")({ head: () => meta("My profile — Univero", "Build a detailed academic profile: grades, test scores, activities, languages and preferences for better matches."), component: ProfilePage });

const sections = ["Personal", "Academic", "Tests", "CV & activities", "Preferences"] as const;
const nationalities = ["Estonia", "Latvia", "Lithuania", "Finland", "Sweden", "Germany", "Netherlands", "France", "Italy", "Spain", "Poland", "Ukraine", "United Kingdom", "United States", "India", "China", "Other"];
const destinations = ["Europe", "Anywhere", "Scandinavia", "Baltics", ...uniCountries];
const preferenceOptions = ["Big city", "Smaller university town", "Large university", "Smaller community", "International environment", "Strong career opportunities", "Campus life", "Prestige/ranking", "Affordable living costs", "Study abroad opportunities"];
const skillSuggestions = ["Programming", "Public speaking", "Leadership", "Design", "Entrepreneurship", "Data analysis", "Writing", "Research"];

function Field({ label, children, className = "" }: { label: string; children: ReactNode; className?: string }) { return <label className={`block ${className}`}><span className="mb-1.5 block text-xs font-bold uppercase text-muted-foreground">{label}</span>{children}</label>; }
const Sel = ({ value, onChange, options, placeholder }: { value: string; onChange: (v: string) => void; options: string[]; placeholder?: string }) => <select value={value} onChange={e => onChange(e.target.value)} className="input-field">{placeholder !== undefined && <option value="">{placeholder}</option>}{options.map(o => <option key={o}>{o}</option>)}</select>;

type EntryKey = "work" | "activities" | "awards" | "projects" | "volunteering";
const entryConfig: Record<EntryKey, { title: string; fields: [keyof Entry, string][] }> = {
  work: { title: "Work experience", fields: [["org", "Organization"], ["role", "Role"], ["start", "Start date"], ["end", "End date"], ["hours", "Hours / week"], ["description", "Description"]] },
  activities: { title: "Extracurricular activities", fields: [["title", "Activity name"], ["role", "Role"], ["org", "Organization"], ["start", "Years involved"], ["hours", "Hours / week"], ["description", "Description"]] },
  awards: { title: "Awards", fields: [["title", "Award name"], ["org", "Organization"], ["start", "Date"], ["description", "Description"]] },
  projects: { title: "Projects", fields: [["title", "Project name"], ["role", "Role"], ["link", "Link"], ["description", "Description"]] },
  volunteering: { title: "Volunteering", fields: [["org", "Organization"], ["role", "Role"], ["description", "Description"]] },
};

function ProfilePage() {
  const { profile: p, docs, ready, updateProfile } = useUnivero();
  const [section, setSection] = useState<(typeof sections)[number]>("Personal"); const [skill, setSkill] = useState("");
  const set = <K extends keyof Profile>(k: K, v: Profile[K]) => updateProfile({ ...p, [k]: v });
  const setYear = (id: string, patch: Partial<SchoolYear>) => set("years", p.years.map(y => (y.id === id ? { ...y, ...patch } : y)));
  const setTest = (id: string, patch: Partial<TestEntry>) => set("tests", p.tests.map(t => (t.id === id ? { ...t, ...patch } : t)));
  const setEntry = (k: EntryKey, id: string, patch: Partial<Entry>) => set(k, p[k].map(e => (e.id === id ? { ...e, ...patch } : e)));
  const toggle = (k: "countries" | "preferences", v: string) => set(k, p[k].includes(v) ? p[k].filter(x => x !== v) : [...p[k], v]);
  const c = completeness(p, docs);
  if (!ready) return <main className="page-shell min-h-[70vh] py-16" />;
  return <main className="page-shell min-h-[70vh] py-12 md:py-16">
    <PageHeader eyebrow="Profile" title="My student profile" subtitle="The more detail you add, the more precise your matches and requirement checks become. Changes save automatically."><Button asChild><Link to="/results">See my matches</Link></Button></PageHeader>
    <div className="mt-8 flex gap-1 overflow-x-auto border-b border-border" role="tablist">{sections.map(s => <button key={s} role="tab" aria-selected={section === s} onClick={() => setSection(s)} className={`shrink-0 border-b-2 px-4 py-3 text-sm font-semibold ${section === s ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"}`}>{s}</button>)}</div>
    <div className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1fr)_300px]"><div className="space-y-6">
      {section === "Personal" && <Card><h2 className="font-display text-xl font-bold text-ink">Personal information</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">
        <Field label="Full name"><input className="input-field" value={p.name} onChange={e => set("name", e.target.value)} placeholder="Angelina Tamm" /></Field>
        <Field label="Date of birth"><input type="date" className="input-field" value={p.dob} onChange={e => set("dob", e.target.value)} /></Field>
        <Field label="Nationality"><Sel value={p.nationality} onChange={v => set("nationality", v)} options={nationalities} placeholder="Select" /></Field>
        <Field label="Country of residence"><Sel value={p.country} onChange={v => set("country", v)} options={nationalities} placeholder="Select" /></Field>
        <Field label="Current school"><input className="input-field" value={p.school} onChange={e => set("school", e.target.value)} placeholder="Tallinn English College" /></Field>
        <Field label="Graduation year"><Sel value={p.graduation} onChange={v => set("graduation", v)} options={["2026", "2027", "2028", "2029"]} /></Field>
        <Field label="Curriculum" className="sm:col-span-2"><Sel value={p.curriculum} onChange={v => set("curriculum", v)} options={curricula} placeholder="Select" /></Field>
      </div><p className="mt-4 text-xs text-muted-foreground">Nationality is used to show EU vs. international tuition where relevant.</p></Card>}

      {section === "Academic" && <>
        <Card><h2 className="font-display text-xl font-bold text-ink">Academic profile</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Overall GPA (4.0 scale)"><input className="input-field" inputMode="decimal" value={p.gpa} onChange={e => set("gpa", e.target.value)} placeholder="3.8" /></Field><Field label="Subject grade scale"><Sel value={p.gradeScale} onChange={v => set("gradeScale", v)} options={gradeScales} /></Field></div></Card>
        {p.years.map(y => <Card key={y.id}><div className="flex flex-wrap items-center gap-3"><input className="input-field max-w-48 font-semibold" value={y.label} onChange={e => setYear(y.id, { label: e.target.value })} aria-label="School year" /><div className="flex rounded-md border border-border p-1">{(["Final", "Predicted"] as const).map(k => <button key={k} onClick={() => setYear(y.id, { kind: k })} className={`rounded px-3 py-1.5 text-xs font-semibold ${y.kind === k ? "bg-primary text-primary-foreground" : "text-muted-foreground"}`}>{k}</button>)}</div><Button size="icon" variant="ghost" className="ml-auto" onClick={() => set("years", p.years.filter(x => x.id !== y.id))} aria-label="Remove year"><Trash2 /></Button></div>
          <table className="mt-4 w-full text-sm"><thead><tr className="text-left text-xs uppercase text-muted-foreground"><th className="pb-2">Subject</th><th className="w-32 pb-2">Grade</th><th className="w-10" /></tr></thead><tbody>{y.subjects.map(s => <tr key={s.id} className="border-t border-border"><td className="py-1.5 pr-2"><input className="w-full bg-transparent py-1.5 outline-none" value={s.name} placeholder="Mathematics" onChange={e => setYear(y.id, { subjects: y.subjects.map(x => (x.id === s.id ? { ...x, name: e.target.value } : x)) })} /></td><td><input className="w-full bg-transparent py-1.5 font-semibold outline-none" value={s.grade} placeholder="5/5" onChange={e => setYear(y.id, { subjects: y.subjects.map(x => (x.id === s.id ? { ...x, grade: e.target.value } : x)) })} /></td><td><button onClick={() => setYear(y.id, { subjects: y.subjects.filter(x => x.id !== s.id) })} aria-label="Remove subject" className="text-muted-foreground hover:text-primary"><X className="size-4" /></button></td></tr>)}</tbody></table>
          <Button size="sm" variant="ghost" className="mt-2" onClick={() => setYear(y.id, { subjects: [...y.subjects, { id: uid(), name: "", grade: "" }] })}><Plus /> Add subject</Button></Card>)}
        <Button variant="outline" onClick={() => set("years", [...p.years, { id: uid(), label: `Grade ${10 + Math.min(p.years.length, 2)}${p.years.length >= 2 ? " predicted" : ""}`, kind: p.years.length >= 2 ? "Predicted" : "Final", subjects: [{ id: uid(), name: "Mathematics", grade: "" }, { id: uid(), name: "English", grade: "" }] }])}><Plus /> Add school year</Button>
      </>}

      {section === "Tests" && <Card><h2 className="font-display text-xl font-bold text-ink">Standardized tests</h2><p className="mt-1 text-sm text-muted-foreground">Add taken and planned tests. Attach certificates in the document vault.</p>
        <div className="mt-5 space-y-3">{p.tests.map(t => <div key={t.id} className="grid gap-3 rounded-md border border-border p-4 sm:grid-cols-[1fr_1fr_1fr_1fr_auto]"><Sel value={t.name} onChange={v => setTest(t.id, { name: v })} options={testNames} /><select value={t.status} onChange={e => setTest(t.id, { status: e.target.value as TestEntry["status"] })} className="input-field"><option>Taken</option><option>Planned</option></select><input className="input-field" placeholder={t.status === "Planned" ? "Target (optional)" : "Score"} value={t.score} onChange={e => setTest(t.id, { score: e.target.value })} /><input type="month" className="input-field" value={t.date} onChange={e => setTest(t.id, { date: e.target.value })} aria-label="Date" /><Button size="icon" variant="ghost" onClick={() => set("tests", p.tests.filter(x => x.id !== t.id))} aria-label="Remove test"><Trash2 /></Button></div>)}</div>
        <div className="mt-4 flex flex-wrap items-center gap-4"><Button variant="outline" onClick={() => set("tests", [...p.tests, { id: uid(), name: "SAT", score: "", date: "", status: "Taken" }])}><Plus /> Add test</Button><label className="flex items-center gap-2 text-sm"><input type="checkbox" className="accent-primary" checked={p.noTests} onChange={e => set("noTests", e.target.checked)} /> I’m applying test-optional where possible</label></div></Card>}

      {section === "CV & activities" && <>
        {(Object.keys(entryConfig) as EntryKey[]).map(k => <Card key={k}><div className="flex items-center justify-between"><h2 className="font-display text-lg font-bold text-ink">{entryConfig[k].title}</h2><Button size="sm" variant="outline" onClick={() => set(k, [...p[k], emptyEntry()])}><Plus /> Add</Button></div>
          {p[k].length === 0 && <p className="mt-3 text-sm text-muted-foreground">Nothing added yet.</p>}
          <div className="mt-4 space-y-4">{p[k].map(e => <div key={e.id} className="grid gap-3 rounded-md border border-border p-4 sm:grid-cols-2">{entryConfig[k].fields.map(([f, label]) => f === "description" ? <Field key={f} label={label} className="sm:col-span-2"><textarea className="input-field !h-20 py-2" value={e[f]} onChange={ev => setEntry(k, e.id, { [f]: ev.target.value })} /></Field> : <Field key={f} label={label}><input className="input-field" value={e[f]} onChange={ev => setEntry(k, e.id, { [f]: ev.target.value })} /></Field>)}<Button size="sm" variant="ghost" className="w-fit" onClick={() => set(k, p[k].filter(x => x.id !== e.id))}><Trash2 /> Remove</Button></div>)}</div></Card>)}
        <Card><h2 className="font-display text-lg font-bold text-ink">Skills</h2><div className="mt-3 flex flex-wrap gap-2">{p.skills.map(s => <span key={s} className="pill bg-secondary text-primary">{s}<button onClick={() => set("skills", p.skills.filter(x => x !== s))} aria-label={`Remove ${s}`}><X className="size-3" /></button></span>)}</div><form className="mt-3 flex gap-2" onSubmit={e => { e.preventDefault(); if (skill.trim() && !p.skills.includes(skill.trim())) set("skills", [...p.skills, skill.trim()]); setSkill(""); }}><input className="input-field" list="skills" value={skill} onChange={e => setSkill(e.target.value)} placeholder="Add a skill" /><datalist id="skills">{skillSuggestions.map(s => <option key={s} value={s} />)}</datalist><Button type="submit" variant="outline" size="lg">Add</Button></form></Card>
        <Card><h2 className="font-display text-lg font-bold text-ink">Languages</h2><div className="mt-3 space-y-2">{p.languages.map(l => <div key={l.id} className="flex gap-2"><input className="input-field" value={l.name} placeholder="English" onChange={e => set("languages", p.languages.map(x => (x.id === l.id ? { ...x, name: e.target.value } : x)))} /><select className="input-field max-w-32" value={l.level} onChange={e => set("languages", p.languages.map(x => (x.id === l.id ? { ...x, level: e.target.value } : x)))}>{languageLevels.map(v => <option key={v}>{v}</option>)}</select><Button size="icon" variant="ghost" onClick={() => set("languages", p.languages.filter(x => x.id !== l.id))} aria-label="Remove language"><Trash2 /></Button></div>)}</div><Button size="sm" variant="outline" className="mt-3" onClick={() => set("languages", [...p.languages, { id: uid(), name: "", level: "B2" }])}><Plus /> Add language</Button></Card>
      </>}

      {section === "Preferences" && <Card><h2 className="font-display text-xl font-bold text-ink">Study preferences</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Subject of interest"><Sel value={p.subject} onChange={v => set("subject", v)} options={subjects} /></Field><Field label="Specific program (optional)"><input className="input-field" value={p.program} onChange={e => set("program", e.target.value)} placeholder="International Business" /></Field><Field label="Career goal" className="sm:col-span-2"><input className="input-field" value={p.careerGoal} onChange={e => set("careerGoal", e.target.value)} placeholder="Consulting, start my own company…" /></Field><Field label={`Tuition budget per year · €${p.budget.toLocaleString()}`} className="sm:col-span-2"><input type="range" min={0} max={70000} step={1000} value={p.budget} onChange={e => set("budget", Number(e.target.value))} className="w-full accent-primary" /></Field></div>
        <label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" className="accent-primary" checked={p.scholarship} onChange={e => set("scholarship", e.target.checked)} /> I need scholarship or financial aid</label>
        <h3 className="mt-6 text-xs font-bold uppercase text-muted-foreground">Preferred destinations</h3><div className="mt-2 flex flex-wrap gap-2">{destinations.map(d => <button key={d} onClick={() => toggle("countries", d)} className={`rounded-md border px-3 py-1.5 text-xs font-semibold ${p.countries.includes(d) ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card"}`}>{d}</button>)}</div>
        <h3 className="mt-6 text-xs font-bold uppercase text-muted-foreground">University environment</h3><div className="mt-2 flex flex-wrap gap-2">{preferenceOptions.map(d => <button key={d} onClick={() => toggle("preferences", d)} className={`rounded-md border px-3 py-1.5 text-xs font-semibold ${p.preferences.includes(d) ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card"}`}>{d}</button>)}</div></Card>}
    </div>
      <aside className="space-y-4"><Card><div className="flex justify-between"><h2 className="font-display text-lg font-bold text-ink">Profile completeness</h2><strong className="text-primary">{c.percent}%</strong></div><Progress value={c.percent} className="my-4" /><Checklist items={c.checks} /></Card><p className="px-1 text-xs text-muted-foreground">Stored only in this browser for the prototype.</p></aside>
    </div></main>;
}
