import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Bookmark, CalendarDays, GitCompareArrows, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, Checklist, EligibilityPill, meta, PageHeader, Progress, UniLogo } from "@/components/univero/bits";
import { applicationStatuses, completeness, daysUntil, getMatch, money, readiness, universities, type AppStatus } from "@/lib/univero";
import { useUnivero } from "@/lib/use-univero";

export const Route = createFileRoute("/shortlist")({ head: () => meta("My shortlist — Univero", "Saved universities with match score, deadlines, eligibility, application readiness and status."), component: Shortlist });

function Shortlist() {
  const { profile, saved, compare, docs, ready, toggleSaved, toggleCompare, statusOf, setStatus } = useUnivero();
  const selected = universities.filter(u => saved.includes(u.id)); const c = completeness(profile, docs);
  const active = selected.filter(u => ["Applying", "Submitted"].includes(statusOf(u.id))).length;
  return <main className="page-shell min-h-[70vh] py-12 md:py-16">
    <PageHeader eyebrow="Your journey" title="My shortlist" subtitle="Everything you need to decide and prepare, for every university you’ve saved."><Button variant="outline" asChild><Link to="/applications">Application board</Link></Button></PageHeader>
    <div className="mt-9 grid gap-5 sm:grid-cols-3"><Card><Bookmark className="size-5 text-primary" /><strong className="mt-4 block font-display text-3xl text-ink">{selected.length}</strong><span className="text-sm text-muted-foreground">Saved universities</span></Card><Card><CalendarDays className="size-5 text-primary" /><strong className="mt-4 block font-display text-3xl text-ink">{active}</strong><span className="text-sm text-muted-foreground">Applications in progress</span></Card><Card><span className="text-xs font-bold uppercase text-primary">Profile</span><strong className="mt-4 block font-display text-3xl text-ink">{ready ? c.percent : "—"}%</strong><span className="text-sm text-muted-foreground">Complete</span><Progress value={c.percent} className="mt-3" /></Card></div>
    <div className="mt-11 grid gap-8 lg:grid-cols-[minmax(0,1fr)_300px]"><div>
      <h2 className="font-display text-xl font-bold text-ink">Saved universities</h2>
      {ready && !selected.length ? <Card className="mt-5 !py-14 text-center"><Bookmark className="mx-auto size-8 text-primary" /><h3 className="mt-4 font-display text-lg font-bold">Your shortlist starts here</h3><p className="mt-2 text-sm text-muted-foreground">Save universities that catch your eye while browsing.</p><Button asChild className="mt-6"><Link to="/results">Explore matches <ArrowRight /></Link></Button></Card> :
        <div className="mt-5 space-y-4">{selected.map(u => { const m = getMatch(u, profile); const r = readiness(u, profile, docs); const d = daysUntil(u.deadlineDate); return <Card key={u.id}>
          <div className="flex flex-wrap items-start gap-4"><UniLogo university={u} /><div className="min-w-0 flex-1"><Link to="/university/$id" params={{ id: u.id }} className="font-display text-lg font-bold text-ink hover:text-primary">{u.name}</Link><p className="text-sm text-muted-foreground">{m.program.name} · <span aria-hidden>{u.flag}</span> {u.city}</p><div className="mt-2 flex flex-wrap gap-2"><EligibilityPill value={m.eligibility} />{u.scholarship && <span className="pill bg-accent text-primary">Scholarships</span>}</div></div><div className="text-right"><strong className="font-display text-2xl text-primary">{m.score}%</strong><p className="text-xs font-bold uppercase text-muted-foreground">Match</p></div></div>
          <div className="mt-5 grid gap-4 border-t border-border pt-4 text-sm sm:grid-cols-4"><div><span className="block text-xs text-muted-foreground">Deadline*</span><strong className={d <= 60 ? "text-warning" : "text-ink"}>{u.deadline}</strong><span className="block text-xs text-muted-foreground">{d > 0 ? `${d} days left` : "Passed"}</span></div><div><span className="block text-xs text-muted-foreground">Tuition*</span><strong className="text-ink">{money(m.tuition)}</strong></div><div className="sm:col-span-2"><div className="flex justify-between text-xs"><span className="text-muted-foreground">Application readiness</span><strong className="text-primary">{r.percent}%</strong></div><Progress value={r.percent} className="mt-2" /><p className="mt-1.5 text-xs text-muted-foreground">{r.checks.filter(x => !x.done).slice(0, 2).map(x => x.label).join(" · ") || "Ready to submit"}</p></div></div>
          <div className="mt-4 flex flex-wrap items-center gap-2"><label className="flex items-center gap-2 text-xs font-semibold text-muted-foreground">Status <select value={statusOf(u.id)} onChange={e => setStatus(u.id, e.target.value as AppStatus)} className="h-9 rounded-md border border-border bg-card px-2 text-xs font-semibold text-foreground">{applicationStatuses.map(s => <option key={s}>{s}</option>)}</select></label><Button size="sm" variant={compare.includes(u.id) ? "secondary" : "outline"} onClick={() => toggleCompare(u.id)} className="ml-auto"><GitCompareArrows /> {compare.includes(u.id) ? "In comparison" : "Compare"}</Button><Button size="sm" variant="ghost" onClick={() => toggleSaved(u.id)} aria-label="Remove from shortlist"><Trash2 /></Button></div>
        </Card>; })}</div>}
    </div>
      <aside className="space-y-4"><Card><h2 className="font-display text-lg font-bold text-ink">Profile checklist</h2><div className="mt-4"><Checklist items={c.checks} /></div></Card><p className="text-xs leading-5 text-muted-foreground">*Illustrative deadlines and tuition. Confirm with each university.</p></aside>
    </div></main>;
}
