import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowLeft, Bookmark, Check, GitCompareArrows } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AdmissionPill, Card, Checklist, EligibilityPill, meta, Progress, RequirementList, UniLogo } from "@/components/univero/bits";
import { useUnivero } from "@/lib/use-univero";
import { getMatch, money, readiness, tuitionFor, universities } from "@/lib/univero";

export const Route = createFileRoute("/university/$id")({
  head: ({ params }) => { const u = universities.find(x => x.id === params.id); return meta(`${u?.name || "University"} — Univero`, `Programs, admissions, costs, scholarships and your personal fit for ${u?.name || "this university"}.`); },
  component: Detail,
});
const tabs = ["Overview", "Programs", "Admissions", "Costs", "Scholarships", "Student Life", "Career", "My Fit"] as const;
const tierLabel = { 1: "Most selective", 2: "Highly selective", 3: "Selective", 4: "Accessible" } as const;

function Row({ label, value }: { label: string; value: React.ReactNode }) { return <div className="flex justify-between gap-4 border-b border-border py-3 text-sm last:border-0"><dt className="text-muted-foreground">{label}</dt><dd className="text-right font-semibold text-ink">{value}</dd></div>; }

function Detail() {
  const { id } = Route.useParams(); const u = universities.find(x => x.id === id);
  const { profile, saved, compare, docs, ready, toggleSaved, toggleCompare } = useUnivero();
  const [tab, setTab] = useState<(typeof tabs)[number]>("Overview"); const [programId, setProgramId] = useState<string>();
  if (!u) return <main className="page-shell min-h-[60vh] py-20"><h1 className="font-display text-3xl font-bold">University not found</h1><Button asChild className="mt-5"><Link to="/explore">Explore universities</Link></Button></main>;
  const m = getMatch(u, profile, programId); const r = readiness(u, profile, docs);
  const gaps = m.requirements.filter(x => x.status !== "met");
  return <main className="page-shell min-h-[70vh] py-10 md:py-14">
    <Link to="/results" className="inline-flex items-center gap-2 text-sm font-semibold text-primary hover:underline"><ArrowLeft className="size-4" /> Back to matches</Link>
    <div className="mt-8 flex flex-wrap items-start justify-between gap-6"><div className="flex gap-5"><UniLogo university={u} size="lg" /><div>
      <p className="text-xs font-bold uppercase text-primary"><span aria-hidden>{u.flag}</span> {u.city}, {u.country}</p>
      <h1 className="mt-2 font-display text-3xl font-bold text-ink md:text-5xl">{u.name}</h1><p className="mt-2 text-muted-foreground">{m.program.name}</p>
      <div className="mt-4 flex flex-wrap gap-2"><EligibilityPill value={m.eligibility} /><AdmissionPill value={m.admission} /><span className="pill bg-muted text-foreground">{u.type}</span></div>
    </div></div>
      <div className="rounded-lg border border-border bg-card px-8 py-6 text-center subtle-shadow"><strong className="font-display text-5xl text-primary">{ready ? m.score : "—"}%</strong><p className="mt-1 text-xs font-bold uppercase text-muted-foreground">Match score</p></div></div>
    <div className="mt-6 flex flex-wrap gap-2"><Button onClick={() => toggleSaved(u.id)}><Bookmark className={saved.includes(u.id) ? "fill-current" : ""} /> {saved.includes(u.id) ? "Saved to shortlist" : "Save to shortlist"}</Button><Button variant="outline" onClick={() => toggleCompare(u.id)}><GitCompareArrows /> {compare.includes(u.id) ? "Remove from comparison" : "Add to comparison"}</Button>{compare.length > 1 && <Button variant="ghost" asChild><Link to="/compare">View comparison</Link></Button>}</div>

    <div className="mt-10 flex gap-1 overflow-x-auto border-b border-border" role="tablist">{tabs.map(t => <button key={t} role="tab" aria-selected={tab === t} onClick={() => setTab(t)} className={`shrink-0 border-b-2 px-4 py-3 text-sm font-semibold ${tab === t ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"}`}>{t}</button>)}</div>

    <div className="mt-8 grid gap-8 lg:grid-cols-[1.6fr_1fr]"><div className="space-y-6">
      {tab === "Overview" && <Card><h2 className="font-display text-xl font-bold text-ink">Overview</h2><dl className="mt-3"><Row label="Location" value={`${u.city}, ${u.country}`} /><Row label="University type" value={u.type} /><Row label="Student population" value={u.students} /><Row label="International students" value={`~${u.intl}%`} /><Row label="Campus type" value={u.campus} /><Row label="Selectivity" value={tierLabel[u.tier]} /><Row label="Programs on Univero" value={u.programs.length} /><Row label="Official website" value={<a href={`https://${u.domain}`} target="_blank" rel="noreferrer" className="text-primary hover:underline">{u.domain}</a>} /></dl><p className="mt-4 text-xs text-muted-foreground">Rankings are not shown until verified data is connected.</p></Card>}
      {tab === "Programs" && <Card><h2 className="font-display text-xl font-bold text-ink">Programs</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[560px] text-sm"><thead><tr className="text-left text-xs uppercase text-muted-foreground"><th className="pb-3">Program</th><th>Duration</th><th>Language</th><th>Tuition*</th><th>Deadline*</th></tr></thead><tbody>{u.programs.map(p => <tr key={p.id} className={`border-t border-border ${p.id === m.program.id ? "bg-accent/40" : ""}`}><td className="py-3 pr-3"><button className="text-left font-semibold text-ink hover:text-primary" onClick={() => setProgramId(p.id)}>{p.name}</button><span className="block text-xs text-muted-foreground">{p.degree}</span></td><td>{p.duration}</td><td>{p.language}</td><td>{money(tuitionFor(p, profile))}</td><td>{p.deadline}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-muted-foreground">Select a program to see its admissions and fit.</p></Card>}
      {tab === "Admissions" && <Card><h2 className="font-display text-xl font-bold text-ink">Admissions · {m.program.name}</h2><dl className="mt-3"><Row label="Academic requirement" value={`Indicative GPA ${m.program.minGpa.toFixed(2)}+`} /><Row label="Required subjects" value={m.program.requiredSubjects.join(", ") || "None specified"} /><Row label="SAT / ACT" value={m.program.sat ? `${u.satRequired ? "Required" : "Recommended"} · ${m.program.sat}+` : "Not required"} /><Row label="English" value={`IELTS ${m.program.ielts} / TOEFL ${Math.round(m.program.ielts * 13.5)} or equivalent`} /><Row label="Other tests" value={m.program.otherTests.join(", ") || "None"} /><Row label="Application deadline" value={m.program.deadline} /></dl><h3 className="mt-6 text-sm font-bold text-ink">Required documents</h3><ul className="mt-2 grid gap-1 text-sm text-muted-foreground sm:grid-cols-2">{m.program.documents.map(d => <li key={d}>• {d}</li>)}</ul></Card>}
      {tab === "Costs" && <Card><h2 className="font-display text-xl font-bold text-ink">Costs</h2><dl className="mt-3"><Row label="Tuition / year (your rate)" value={money(m.tuition)} />{u.tuitionEU !== u.tuition && <Row label="EU / non-EU tuition" value={`${money(u.tuitionEU)} / ${money(u.tuition)}`} />}<Row label="Est. accommodation / month" value={money(u.accommodation)} /><Row label="Est. monthly living cost" value={money(Math.round(u.living / 12 / 10) * 10)} /><Row label="Est. total first year" value={money(m.tuition + u.living)} /><Row label="Your tuition budget" value={money(profile.budget)} /></dl><span className={`pill mt-4 ${m.affordability === "Within budget" ? "bg-success-soft text-success" : "bg-warning-soft text-warning"}`}>{m.affordability}</span></Card>}
      {tab === "Scholarships" && <Card><h2 className="font-display text-xl font-bold text-ink">Scholarships</h2>{u.scholarships.length ? <div className="mt-4 space-y-3">{u.scholarships.map(s => <div key={s.name} className="rounded-md border border-border p-4"><strong className="text-ink">{s.name}</strong><dl className="mt-2 grid gap-2 text-sm sm:grid-cols-3"><div><dt className="text-xs text-muted-foreground">Amount</dt><dd>{s.amount}</dd></div><div><dt className="text-xs text-muted-foreground">Eligibility</dt><dd>{s.eligibility}</dd></div><div><dt className="text-xs text-muted-foreground">Deadline</dt><dd>{s.deadline}</dd></div></dl></div>)}</div> : <p className="mt-3 text-sm text-muted-foreground">No scholarships listed for international bachelor’s students yet.</p>}</Card>}
      {tab === "Student Life" && <Card><h2 className="font-display text-xl font-bold text-ink">Student life</h2><dl className="mt-3"><Row label="Setting" value={u.setting} /><Row label="Campus" value={u.campus} /><Row label="Community size" value={u.size} /><Row label="International community" value={`~${u.intl}% international`} /></dl><div className="mt-4 flex flex-wrap gap-2">{u.tags.map(t => <span key={t} className={`pill ${profile.preferences.includes(t) ? "bg-success-soft text-success" : "bg-muted text-foreground"}`}>{t}</span>)}</div></Card>}
      {tab === "Career" && <Card><h2 className="font-display text-xl font-bold text-ink">Career</h2><p className="mt-3 text-sm text-foreground">{u.career}.</p><dl className="mt-3"><Row label="Career fit for you" value={`${m.fit.career}/10`} /><Row label="Your career goal" value={profile.careerGoal || "Not set"} /></dl>{!profile.careerGoal && <Button asChild size="sm" variant="outline" className="mt-4"><Link to="/profile">Add a career goal</Link></Button>}</Card>}
      {tab === "My Fit" && <Card><h2 className="font-display text-xl font-bold text-ink">My fit</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{([["Academic fit", m.fit.academic], ["Financial fit", m.fit.financial], ["Location fit", m.fit.location], ["Program fit", m.fit.program], ["Career fit", m.fit.career], ["Personal fit", m.fit.personal]] as const).map(([l, v]) => <div key={l}><div className="flex justify-between text-sm"><span className="text-muted-foreground">{l}</span><strong className="text-ink">{v}/10</strong></div><Progress value={v * 10} className="mt-2" /></div>)}</div><div className="mt-6 flex items-center justify-between rounded-md bg-accent/60 px-5 py-4"><span className="font-semibold text-ink">Overall</span><strong className="font-display text-2xl text-primary">{m.score}% Match</strong></div><h3 className="mt-6 text-sm font-bold text-ink">Why</h3><ul className="mt-2 space-y-1.5">{m.reasons.map(x => <li key={x} className="flex items-center gap-2 text-sm"><Check className="size-4 text-success" />{x}</li>)}</ul></Card>}
    </div>
      <aside className="space-y-5">
        <Card><div className="flex items-center justify-between"><h2 className="font-display text-lg font-bold text-ink">Requirements check</h2><EligibilityPill value={m.eligibility} /></div><div className="mt-4"><RequirementList items={m.requirements} /></div>{gaps.length > 0 && <Button asChild size="sm" className="mt-5 w-full"><Link to="/profile">Update profile</Link></Button>}</Card>
        <Card><div className="flex items-center justify-between"><h2 className="font-display text-lg font-bold text-ink">Application readiness</h2><strong className="text-primary">{r.percent}%</strong></div><Progress value={r.percent} className="my-4" /><Checklist items={r.checks} /></Card>
        <p className="text-xs leading-5 text-muted-foreground">*All figures, requirements and dates are illustrative prototype data, not verified admission information. The Match Score describes overall fit, not your chance of admission.</p>
      </aside></div>
  </main>;
}
