import { Link } from "@tanstack/react-router";
import { ArrowUpRight, Bookmark, Check, GitCompareArrows, MapPin } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getMatch, money, type Profile, type University } from "@/lib/univero";

export function MatchCard({ university: u, profile, saved, compared, onSave, onCompare }: { university: University; profile: Profile; saved: boolean; compared: boolean; onSave: (id: string) => void; onCompare: (id: string) => void }) {
  const match = getMatch(u, profile);
  return <article className="rounded-lg border border-border bg-card p-5 subtle-shadow transition-transform hover:-translate-y-0.5 md:p-6">
    <div className="flex flex-col gap-5 sm:flex-row sm:justify-between">
      <div className="flex min-w-0 gap-4"><div className="flex size-12 shrink-0 items-center justify-center rounded-md bg-secondary font-display text-lg font-bold text-primary">{u.name.split(" ").map(w => w[0]).slice(0, 2).join("")}</div><div><div className="flex items-center gap-2"><p className="text-xs font-bold uppercase text-primary">{u.country}</p></div><h3 className="mt-1 font-display text-lg font-bold text-ink">{u.name}</h3><p className="mt-1 text-sm text-muted-foreground">{u.program}</p><p className="mt-2 flex items-center gap-1 text-xs text-muted-foreground"><MapPin className="size-3.5" /> {u.city}, {u.country}</p></div></div>
      <div className="flex shrink-0 items-center gap-3 sm:flex-col sm:items-end sm:gap-0"><span className="font-display text-3xl font-bold text-primary">{match.score}%</span><span className="text-xs font-bold uppercase text-muted-foreground">Match score</span></div>
    </div>
    <div className="mt-5 flex flex-wrap gap-2"><span className={`pill ${match.eligibility === "Eligible" ? "bg-success-soft text-success" : match.eligibility === "Not eligible" ? "bg-warning-soft text-warning" : "bg-secondary text-primary"}`}>{match.eligibility}</span><span className="pill bg-muted text-foreground">{u.competitiveness}</span><span className={`pill ${match.affordability === "Within budget" ? "bg-success-soft text-success" : "bg-warning-soft text-warning"}`}>{match.affordability}</span>{u.scholarship && <span className="pill bg-accent text-primary">Scholarships</span>}</div>
    <div className="mt-5 grid grid-cols-2 gap-4 border-y border-border py-4 text-sm sm:grid-cols-3"><div><span className="block text-xs text-muted-foreground">Tuition / year*</span><strong className="mt-1 block text-ink">{money(u.tuition)}</strong></div><div><span className="block text-xs text-muted-foreground">Language</span><strong className="mt-1 block text-ink">{u.language}</strong></div><div className="hidden sm:block"><span className="block text-xs text-muted-foreground">Degree</span><strong className="mt-1 block text-ink">Bachelor’s</strong></div></div>
    <div className="mt-4"><p className="text-xs font-bold uppercase text-muted-foreground">Why it matches</p><div className="mt-2 flex flex-wrap gap-x-5 gap-y-1">{match.reasons.slice(0, 3).map(reason => <span key={reason} className="flex items-center gap-1.5 text-xs text-foreground"><Check className="size-3.5 text-success" />{reason}</span>)}</div></div>
    <div className="mt-5 flex flex-wrap items-center gap-2"><Button size="sm" asChild><Link to="/university/$id" params={{ id: u.id }}>View university <ArrowUpRight /></Link></Button><Button size="sm" variant={compared ? "secondary" : "outline"} onClick={() => onCompare(u.id)} title={compared ? "Remove from comparison" : "Add to comparison"}><GitCompareArrows /> {compared ? "Added" : "Compare"}</Button><Button size="sm" variant={saved ? "secondary" : "ghost"} onClick={() => onSave(u.id)} title={saved ? "Remove from shortlist" : "Save to shortlist"}><Bookmark className={saved ? "fill-current" : ""} /> {saved ? "Saved" : "Save"}</Button></div>
  </article>;
}